//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cumain
    {
        public int CUSTNO { get; set; }
        public string CUSTCODE { get; set; }
        public string CUSTNAME { get; set; }
        public short TYPENO { get; set; }
        public string ADDRESS { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string ADDRESS4 { get; set; }
        public string ADDRESS5 { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string INFO { get; set; }
        public string FIRM { get; set; }
        public Nullable<short> CUSTGROUPNO { get; set; }
        public string SPAMBYEMAIL { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string PASSIVE { get; set; }
        public decimal DISCOUNT { get; set; }
        public Nullable<short> DISCCLASS { get; set; }
        public Nullable<short> PRICEGROUPNO { get; set; }
        public System.DateTime LASTCHANGE { get; set; }
        public System.DateTime CREATED { get; set; }
    }
}
