//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class eligibility
    {
        public int ELIGIBILITYNO { get; set; }
        public short TYPENO { get; set; }
        public Nullable<int> IDNO { get; set; }
        public decimal THRESHOLDAMOUNT { get; set; }
        public decimal THRESHOLDQUANTITY { get; set; }
        public decimal LIMITAMOUNT { get; set; }
        public decimal LIMITQUANTITY { get; set; }
        public Nullable<int> MASTERELIGIBILITYNO { get; set; }
        public Nullable<short> STOCKNO { get; set; }
        public System.DateTime LASTCHANGE { get; set; }
        public System.DateTime CREATED { get; set; }
    }
}
