//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int INVNO { get; set; }
        public string INVOICE1 { get; set; }
        public string CUSTCODE { get; set; }
        public int TYPE { get; set; }
        public System.DateTime INVOICEDATE { get; set; }
        public string CUSTNAME { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string ADDRESS4 { get; set; }
        public string ADDRESS5 { get; set; }
        public string COMMENT { get; set; }
        public string OINFO { get; set; }
        public string REFNUM { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> VATAMOUNT { get; set; }
        public Nullable<short> STOCKNO { get; set; }
        public Nullable<short> CAUSENO { get; set; }
        public Nullable<short> CUSTPERSONNO { get; set; }
        public Nullable<short> TABLENO { get; set; }
    }
}
