//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockcod
    {
        public short STOCKNO { get; set; }
        public string STOCKCODE { get; set; }
        public string STOCKNAME { get; set; }
        public System.DateTime LASTCHANGE { get; set; }
        public System.DateTime CREATED { get; set; }
    }
}
