//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class userdata
    {
        public int Id { get; set; }
        public int userid { get; set; }
        public string firstname { get; set; }
        public string lasname { get; set; }
        public string contact_email { get; set; }
        public string contact_phone { get; set; }
        public string company_name { get; set; }
        public string delivery_name { get; set; }
        public string delivery_email { get; set; }
        public string delivery_phone { get; set; }
        public string delivery_address1 { get; set; }
        public string delivery_address2 { get; set; }
        public byte[] delivery_suburb { get; set; }
        public string delivery_postcode { get; set; }
        public string delivery_state { get; set; }
        public string delivery_contry { get; set; }
        public string billing_name { get; set; }
        public string billing_email { get; set; }
        public string billing_phone { get; set; }
        public string billing_address1 { get; set; }
        public string billing_address2 { get; set; }
        public string billing_suburb { get; set; }
        public string billing_poscode { get; set; }
        public string billing_state { get; set; }
        public string billing_country { get; set; }
    }
}
