//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class artdimension
    {
        public int LINENO { get; set; }
        public int ARTNO { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> LEN { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public string FRAGILE { get; set; }
        public System.DateTime LASTCHANGE { get; set; }
        public System.DateTime CREATED { get; set; }
    }
}
