//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class artgrp
    {
        public int GROUPNO { get; set; }
        public string GROUPCODE { get; set; }
        public string GROUPNAME { get; set; }
        public Nullable<int> METAGROUPNO { get; set; }
        public string EXPORTABLE { get; set; }
        public System.DateTime LASTCHANGE { get; set; }
        public System.DateTime CREATED { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CodeLanguage { get; set; }
        public Nullable<int> IdCurrentItem { get; set; }
    }
}
