
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1
{

using System;
    using System.Collections.Generic;
    
public partial class catalogue
{

    public int Id { get; set; }

    public string CatalogueCode { get; set; }

    public string CatalogueName { get; set; }

    public int MetaGroupId { get; set; }

}

}
