
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1
{

using System;
    using System.Collections.Generic;
    
public partial class cuperson
{

    public int CUSTPERSONNO { get; set; }

    public string CUSTPERSONNAME { get; set; }

    public string PERSONCODE { get; set; }

    public int CUSTNO { get; set; }

    public Nullable<short> STATUSNO { get; set; }

    public System.DateTime REGDATE { get; set; }

    public Nullable<System.DateTime> VALIDDATE { get; set; }

    public string PHONE { get; set; }

    public string EMAIL { get; set; }

    public string INFO { get; set; }

    public string POSONLY { get; set; }

    public string CUSTPERSONCODE { get; set; }

    public System.DateTime LASTCHANGE { get; set; }

    public System.DateTime CREATED { get; set; }

}

}
