//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class email
    {
        public int id { get; set; }
        public string nameproduct { get; set; }
        public string email1 { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string quantity { get; set; }
        public Nullable<int> status { get; set; }
        public System.DateTime createdate { get; set; }
        public System.DateTime responedate { get; set; }
        public Nullable<int> type { get; set; }
    }
}
