//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FileName { get; set; }
        public string Kind { get; set; }
        public string Description { get; set; }
        public System.DateTime UploadDate { get; set; }
        public string UploadBy { get; set; }
        public string Status { get; set; }
        public string FileAddress { get; set; }
    }
}
