//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_log
    {
        public long INVOICE_LOG_ID { get; set; }
        public System.DateTime EVENT_TIME { get; set; }
        public string WEB_INVOICE { get; set; }
        public System.DateTime WEB_INVOICE_DATE { get; set; }
        public string INVOICE { get; set; }
        public System.DateTime INVOICE_DATE { get; set; }
        public short TYPE { get; set; }
        public Nullable<short> CLASS { get; set; }
        public string STATUS { get; set; }
        public System.DateTime CREATED { get; set; }
    }
}
