
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1
{

using System;
    using System.Collections.Generic;
    
public partial class item
{

    public int ARTNO { get; set; }

    public string ARTCODE { get; set; }

    public string ARTNAME { get; set; }

    public string LONGNAME { get; set; }

    public short ARTTYPE { get; set; }

    public string EXPORTABLE { get; set; }

    public string STOCKITEM { get; set; }

    public Nullable<int> PRODUCERNO { get; set; }

    public Nullable<int> CATEGORYNO { get; set; }

    public Nullable<int> COLORNO { get; set; }

    public string INFO { get; set; }

    public Nullable<decimal> WEBPRICE { get; set; }

    public string SPECIALOFFER { get; set; }

    public string PICTURENAME { get; set; }

    public Nullable<System.DateTime> NEWUNTIL { get; set; }

    public Nullable<int> GROUPNO { get; set; }

    public string AUTHORIZABLE { get; set; }

    public string RESTRICTED { get; set; }

    public string NOTPOST { get; set; }

    public string NOTADDPOSTAGEFEE { get; set; }

    public Nullable<decimal> WEIGHT { get; set; }

    public string COLLATIONUNIT { get; set; }

    public string INFO1 { get; set; }

    public string INFO2 { get; set; }

    public string INFO3 { get; set; }

    public string INFO4 { get; set; }

    public string INFO5 { get; set; }

    public string INFO6 { get; set; }

    public Nullable<decimal> LEN { get; set; }

    public Nullable<decimal> HEIGHT { get; set; }

    public Nullable<decimal> WIDTH { get; set; }

    public string UNITNAME { get; set; }

    public string UNITDESCR { get; set; }

    public string CHECKBOX1 { get; set; }

    public string CHECKBOX2 { get; set; }

    public string CHECKBOX3 { get; set; }

    public string CHECKBOX4 { get; set; }

    public string CHECKBOX5 { get; set; }

    public string CHECKBOX6 { get; set; }

    public Nullable<decimal> VAT { get; set; }

    public Nullable<decimal> PACKAGEVOLUME { get; set; }

    public Nullable<decimal> PACKAGEVOLUME2 { get; set; }

    public Nullable<short> SIZENO { get; set; }

    public Nullable<short> SIZETBLNO { get; set; }

    public Nullable<short> SUPPLYCYCLENO { get; set; }

    public Nullable<short> DISCGROUP { get; set; }

    public Nullable<int> WEBID { get; set; }

    public string PAYMENTTERM { get; set; }

    public System.DateTime LASTCHANGE { get; set; }

    public System.DateTime CREATED { get; set; }

    public Nullable<bool> IsBestSeller { get; set; }

}

}
