//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public long ocid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string companyname { get; set; }
        public string tradingname { get; set; }
        public string promotionName { get; set; }
        public string abn { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
        public string addr3 { get; set; }
        public string postcode { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public Nullable<int> country { get; set; }
        public string showsubtotal { get; set; }
        public Nullable<int> clientID { get; set; }
        public Nullable<System.DateTime> submitDate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public string visible { get; set; }
        public string tradeterms { get; set; }
        public Nullable<float> ordertotal { get; set; }
        public Nullable<float> ordertotalexc { get; set; }
        public string status { get; set; }
        public string currency { get; set; }
        public Nullable<float> exchangerate { get; set; }
        public Nullable<int> profileID { get; set; }
        public Nullable<System.DateTime> closedDate { get; set; }
        public string d_attention { get; set; }
        public string d_fname { get; set; }
        public string d_lname { get; set; }
        public string d_addr1 { get; set; }
        public string d_addr2 { get; set; }
        public string d_addr3 { get; set; }
        public string d_postcode { get; set; }
        public string d_companyname { get; set; }
        public string d_country { get; set; }
        public string d_email { get; set; }
        public string d_mobile { get; set; }
        public string d_phone { get; set; }
        public string d_fax { get; set; }
        public string d_notes { get; set; }
        public string payoption { get; set; }
        public string tobeinvoiced { get; set; }
        public string order_group { get; set; }
        public string d_status { get; set; }
        public string b_attention { get; set; }
        public string b_fname { get; set; }
        public string b_lname { get; set; }
        public string b_companyname { get; set; }
        public string b_abn { get; set; }
        public string b_addr1 { get; set; }
        public string b_addr2 { get; set; }
        public string b_addr3 { get; set; }
        public string b_postcode { get; set; }
        public string b_country { get; set; }
        public string b_mobile { get; set; }
        public string b_phone { get; set; }
        public string b_fax { get; set; }
        public string b_email { get; set; }
        public Nullable<int> b_addrid { get; set; }
        public string onhold { get; set; }
        public Nullable<int> ocupdatedby { get; set; }
        public Nullable<System.DateTime> oclastupdated { get; set; }
        public string notes { get; set; }
    }
}
