//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public long prodetailid { get; set; }
        public long ocid { get; set; }
        public string ocdetailcode { get; set; }
        public string ocdetailname { get; set; }
        public Nullable<int> ocdetailqty { get; set; }
        public Nullable<float> ocdetailprice { get; set; }
        public Nullable<float> ocdetailgst { get; set; }
        public Nullable<int> imagepath { get; set; }
        public string itemtype { get; set; }
        public Nullable<sbyte> totalrequest { get; set; }
        public Nullable<sbyte> qtysent { get; set; }
        public Nullable<float> taxRate { get; set; }
        public Nullable<float> PriceInTax { get; set; }
        public Nullable<float> PriceExTax { get; set; }
        public int itemId { get; set; }
    }
}
