//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class outitem
    {
        public int INVNO { get; set; }
        public int LINENO { get; set; }
        public int ARTNO { get; set; }
        public decimal QTY { get; set; }
        public decimal AMOUNT { get; set; }
        public Nullable<decimal> VATAMOUNT { get; set; }
        public string RCOMMENT { get; set; }
        public Nullable<short> SIZENO { get; set; }
    }
}
