
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1
{

using System;
    using System.Collections.Generic;
    
public partial class payment
{

    public int INVNO { get; set; }

    public int LINENO { get; set; }

    public decimal AMOUNT { get; set; }

    public System.DateTime PAYDATE { get; set; }

    public string PAYDOC { get; set; }

}

}
