//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotionrule
    {
        public int PROMOTIONRULENO { get; set; }
        public int PROMOTIONNO { get; set; }
        public int ELIGIBILITYNO { get; set; }
        public short TYPENO { get; set; }
        public short ADJUSTMENTTYPENO { get; set; }
        public Nullable<decimal> ADJUSTMENTVALUE { get; set; }
        public Nullable<short> PRICEGROUPNO { get; set; }
        public System.DateTime LASTCHANGE { get; set; }
        public System.DateTime CREATED { get; set; }
        public string PROMOTIONCODE { get; set; }
    }
}
