//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion
    {
        public int PROMOTIONNO { get; set; }
        public string PROMOTIONCODE { get; set; }
        public string PROMOTIONNAME { get; set; }
        public short TYPENO { get; set; }
        public string FIRSTDATE { get; set; }
        public string LASTDATE { get; set; }
        public System.DateTime LASTCHANGE { get; set; }
        public System.DateTime CREATED { get; set; }
        public string VALUEPROMOTION { get; set; }
        public int QUANTITY { get; set; }
    }
}
