//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class seo
    {
        public int id { get; set; }
        public string googleanalys { get; set; }
        public string metatag { get; set; }
        public Nullable<int> type { get; set; }
        public string description { get; set; }
        public string page { get; set; }
        public string title { get; set; }
        public string keyword { get; set; }
        public string link { get; set; }
    }
}
