//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> typeId { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public string description { get; set; }
        public string urlimage { get; set; }
        public string link { get; set; }
        public Nullable<int> order { get; set; }
        public string code { get; set; }
    }
}
