
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1
{

using System;
    using System.Collections.Generic;
    
public partial class supplycycle
{

    public short SUPPLYCYCLENO { get; set; }

    public string SUPPLYCYCLECODE { get; set; }

    public string SUPPLYCYCLENAME { get; set; }

    public System.DateTime LASTCHANGE { get; set; }

    public System.DateTime CREATED { get; set; }

}

}
