//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class trans_log
    {
        public long TRANS_LOG_ID { get; set; }
        public string TABLE_NAME { get; set; }
        public int ID { get; set; }
        public string EVENT_CODE { get; set; }
        public System.DateTime EVENT_TIME { get; set; }
        public short RETRY_COUNT { get; set; }
    }
}
