//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_disc_rule
    {
        public string PROMOTIONCODE { get; set; }
        public string PROMOTIONNAME { get; set; }
        public System.DateTime FIRSTDATE { get; set; }
        public Nullable<System.DateTime> LASTDATE { get; set; }
        public Nullable<int> DISCGROUP { get; set; }
        public Nullable<int> DISCCLASS { get; set; }
        public decimal THRESHOLDQUANTITY { get; set; }
        public decimal LIMITQUANTITY { get; set; }
        public decimal THRESHOLDAMOUNT { get; set; }
        public decimal LIMITAMOUNT { get; set; }
        public short ADJUSTMENTTYPENO { get; set; }
        public Nullable<decimal> ADJUSTMENTVALUE { get; set; }
        public Nullable<short> PRICEGROUPNO { get; set; }
        public Nullable<short> STOCKNO { get; set; }
        public System.DateTime LASTCHANGE { get; set; }
        public System.DateTime CREATED { get; set; }
    }
}
